version: "3.8"
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: mimir-dynamo
    ports:
      - "8000:8000"
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb" ]
    volumes:
      - "./dynamodb_data:/data"

#  awscli:
#    image: amazon/aws-cli
#    depends_on:
#      - dynamodb
#    container_name: mimir-awscli
#    volumes:
#      - "./dynamodb_data:/data"
#    environment:
#      - AWS_ACCESS_KEY_ID=dummy_access_key
#      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
#      - AWS_DEFAULT_REGION=ap-southeast-2
#    entrypoint: ["sh", "-c"]
#    command: >
#      "if ! aws dynamodb describe-table --table-name mimir --endpoint-url http://dynamodb:8000 --region ap-southeast-2 > /dev/null 2>&1; then \
#      aws dynamodb create-table --table-name mimir \
#      --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S AttributeName=GSI1PK,AttributeType=S AttributeName=GSI1SK,AttributeType=S \
#      --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
#      --global-secondary-indexes '[{\"IndexName\": \"GSI1\",\"KeySchema\": [{\"AttributeName\":\"GSI1PK\",\"KeyType\":\"HASH\"},{\"AttributeName\":\"GSI1SK\",\"KeyType\":\"RANGE\"}],\"Projection\":{\"ProjectionType\":\"ALL\"}}]' \
#      --billing-mode PAY_PER_REQUEST --endpoint-url http://dynamodb:8000 --region ap-southeast-2; \
#      fi"