version: "3.8"
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: mimir-dynamo
    ports:
      - "8000:8000"
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb" ]
    volumes:
      - "./dynamodb_data:/data"