branch-defaults:
  default:
    environment: null
    group_suffix: null
  use-openai-nuget:
    environment: mimir-api
global:
  application_name: mimir-api
  branch: null
  default_ec2_keyname: mimir-ssh
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
